name: "Bug Report"
description: Report a bug with ZS Language or its extension
title: "[Bug] <short description>"
labels: ["bug"]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Clearly describe the issue or incorrect behavior.
      placeholder: "Example: Keyword highlighting fails when using uppercase"
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Explain how to reproduce the bug.
      placeholder: 1. Open .zs file... 2. Use keyword X... 3. See error
  - type: textarea
    id: expected
    attributes:
      label: What did you expect?
      description: What should have happened instead?
  - type: input
    id: vscode-version
    attributes:
      label: VS Code Version
      placeholder: "e.g. 1.85.0"
  - type: input
    id: extension-version
    attributes:
      label: ZS Language Extension Version
      placeholder: "e.g. 0.0.1"
