name: "ZS Grammar or Syntax Suggestion"
description: Suggest a change or addition to ZS Language grammar
title: "[Syntax] <your suggestion>"
labels: ["grammar", "language-design"]
body:
  - type: textarea
    id: suggestion
    attributes:
      label: What grammar/syntax should be added or changed?
      placeholder: Example: Replace `{}` function nouns with `<>` to avoid block conflict
    validations:
      required: true
  - type: textarea
    id: reason
    attributes:
      label: Why this change?
      description: Explain the benefit or logic behind your suggestion
